kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: istio-system
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: discord
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
    receivers:
    - name: discord
      webhook_configs:
        - url: http://alertmanager-discord:9094
