apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 35.221.47.224  
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 20000
    targetPort: 20000
    protocol: TCP
    name: beacon-relay
  - port: 20001
    targetPort: 20001
    protocol: TCP
    name: beacon-bootnode
  selector:
    app: nginx-ingress
