apiVersion: v1
data:
  private_key: jQibEmxtsf71E+8OuTUxNAQTKK7G8cwslc/oD84QRuKTa+s3pGSy890XtbQIASbZ/oZ7zt6yVS8uuAILPqnM+KfOtvZihzVLBJ3o4qgPORVMw10i1bwzy/gEVcpSmmee.lzpeo+sQHCQIQYM1.WyjzRoKLkKxZ2lr8kOxheQ==
  public_key: nTj8LizZ5Lcxpo80SZr3/ArU2fAqPam1nqK6iKW7mhSlN8+s2eTZhdeuX5VBSj6NvFcGzafX91+0Vr49Sn/iDwFWQpKEF6pg9VZLaof5G+Xd09l7LBWWNmszJ7R8sBugYWdH3sT1b5EamLvK+b/oDL/Our6FK5/QrldpdDS8rQHwBBIghp3+9pW2Q8XvU2TeHHuOH07P/m1o4I1F2HuLRQ9CNo88u2UPEer6o27mO5WVa6JeTJ/JfKzWIZYNnu0v.FJVfuDg09LE83EQ1.+1UgfraYgYYHUvEtkX2DLw==
kind: Secret
metadata:
  name: geth-bootnode-secret
  namespace: pow
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/prysmaticlabs/locations/global/keyRings/prysmatic-k8s-secrets/cryptoKeys/testkey:CiQAaKPz55gg9s1oelF+GqLY4XCnHjd53I+ZcA9V6Ppg/JtgRjMSSQD23sIskpIEbBnbuvYAF/teEPC/aqmcD8NRLYvW6RSCfzChQftM0XiwwCvll7IN4y2iMzMjA+R09dyE/28hkGOA245jxH1VhAM=
# kubesec:mac:sIbZWb/nAjt/irSw.PbpahngOYdBmYpkUjysxOw==
