apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth1monitor
  namespace: pow
spec:
  selector:
    matchLabels:
      app: eth1monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: eth1monitor
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
    spec:
      priorityClassName: monitoring-priority
      containers:
      - name: monitor
        image: gcr.io/prysmaticlabs/eth1monitor:latest
        args:
        - --port=9090
        - --addresses=/etc/config/addresses.txt
        - --web3-provider=http://public-rpc-nodes.pow.svc.cluster.local:8545
        volumeMounts:
        - name: addresses
          mountPath: /etc/config
          readOnly: true
      - name: configmap-reload
        image: jimmidyson/configmap-reload:v0.2.2
        args: 
        - --volume-dir=/etc/config
        - --webhook-url=http://localhost:9090/reload
        volumeMounts:
        - name: addresses
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: addresses
        configMap:
          name: eth1-addresses

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eth1-addresses
  namespace: pow
data:
  addresses.txt: |
    faucet:0xae1f3f522cfb1b0ed128819e8e72fda207c47e5e
    pk-manager:0x1bcd2c7dd8d5ffd8b789d90c71ac9aab55e51d5d
    prylabs:0xd9a5179f091d85051d3c982785efd1455cec8699

