apiVersion: v1
kind: Secret
metadata:
  name: geth-genesis
data:
  json: eyJjb25maWciOnsiY2hhaW5JZCI6MTMzNywiaG9tZXN0ZWFkQmxvY2siOjAsImVpcDE1NUJsb2NrIjowLCJlaXAxNThCbG9jayI6MH0sImRpZmZpY3VsdHkiOiIweDQwMCIsImdhc0xpbWl0IjoiMHgyMTAwMDAwIiwiYWxsb2MiOnsiNzE3YzNhNmU0Y2JkNDc2YzIzMTI2MTIxNTVlYjIzM2JmNDk4ZGQ1YiI6eyJiYWxhbmNlIjoiMHgxMzM3MDAwMDAwMDAwMDAwMDAwMDAwIn19fQo=
type: Opaque