kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: beacon-chain
  namespace: beacon-chain
spec:
  replicas: 3
  serviceName: beacon-chain
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: beacon-chain
      universe: beacon-chain
  template:
    metadata:
      labels:
        component: beacon-chain
        universe: beacon-chain
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        # Disable sidecar proxy for p2p.
        traffic.sidecar.istio.io/excludeInboundPorts: '5000'
        traffic.sidecar.istio.io/includeInboundPorts: '*'
        traffic.sidecar.istio.io/includeOutboundIPRanges: ''
    spec:
      priorityClassName: production-priority
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  component: beacon-chain
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    component: beacon-chain
                topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
        - name: beacon-chain
          image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
          args: 
            - --web3provider=ws://public-rpc-nodes.pow.svc.cluster.local:8546
            #- --verbosity=debug
            - --deposit-contract=$(DEPOSIT_CONTRACT_ADDRESS)
            - --rpc-port=4000
            - --monitoring-port=9090
            - --bootstrap-node=/dns4/bootnode/tcp/$(BOOTNODE_SERVICE_PORT)/p2p/QmQEe7o6hKJdGdSkJRh7WJzS6xrex5f4w2SPR6oWbJNriw
            - --relay-node=/ip4/35.224.249.2/tcp/30000/p2p/QmfAgkmjiZNZhr2wFN9TwaRgHouMTBT6HELyzE5A3BT2wK
            - --p2p-port=5000
            - --enable-tracing
            - --tracing-endpoint=http://jaeger-collector.istio-system.svc.cluster.local:14268
            - --trace-sample-fraction=1.0
            - --datadir=/data
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
          volumeMounts:
          - mountPath: /data
            name: beacondb
          ports:
            - containerPort: 4000
              name: grpc
            - containerPort: 5000
              name: p2p
            - containerPort: 9090
              name: prometheus
          env:
            - name: DEPOSIT_CONTRACT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: beacon-config
                  key: DEPOSIT_CONTRACT_ADDRESS
          readinessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 4000
  volumeClaimTemplates:
  - metadata:
      name: beacondb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
