apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployvrc
  namespace: beacon-chain
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployvrc
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployvrc
subjects:
- kind: ServiceAccount
  name: deployvrc
  namespace: beacon-chain
roleRef:
  kind: ClusterRole
  name: deployvrc
  apiGroup: rbac.authorization.k8s.io

